# Schema for the configuration files of the uc_authorizenet module.

payment_method.settings.authorizenet:
  type: mapping
  label: 'Authorize.net settings'
  mapping:
    duplicate_window:
      type: int
      label: 'Number of seconds to suppress duplicate posts'
    api:
      type: mapping
      label: 'API settings'
      mapping:
        login_id:
          type: string
          label: 'API username'
        transaction_key:
          type: string
          label: 'API password'
        test_gateway_url:
          type: uri
          label: 'API signature'
        live_gateway_url:
          type: uri
          label: 'API signature'
    aim:
      type: mapping
      label: 'AIM settings'
      mapping:
        txn_mode:
          type: string
          label: 'Payment action'
        email_customer:
          type: boolean
          label: 'Submit method'
        response_debug:
          type: boolean
          label: 'IPN debug flag'
    cim:
      type: mapping
      label: 'CIM settings'
      mapping:
        cim_mode:
          type: string
          label: 'Shipping not included'
        cim_profile:
          type: boolean
          label: 'IPN debug flag'
    arb:
      type: mapping
      label: 'ARB settings'
      mapping:
        arb_mode:
          type: string
          label: 'Select address'
        md5_hash:
          type: string
          label: 'Select address'
        report_arb_post:
          type: boolean
          label: 'IPN debug flag'
