# Schema for uc_country country configuration files.

uc_country.country.*:
  type: config_entity
  label: 'Country ISO-3166 data'
  mapping:
    name:
      type: label
      label: 'English short name'
    alpha_2:
      type: string
      label: '2-character country code'
    alpha_3:
      type: string
      label: '3-character country code'
    numeric:
      type: integer
      label: '3-digit country code'
    status:
      type: boolean
      label: 'True if enabled for use'
    zones:
      type: sequence
      label: 'ISO 3166-2 zone name keyed by zone code'
      sequence:
        type: label
        label: 'Zone name'
    address_format:
      type: sequence
      label: 'Address formatting'
      sequence:
        type: string
        label: 'Line item type label'
