uc_ups.settings:
  type: config_object
  label: ''
  mapping:
    access_license:
      type: string
      label: ''
    shipper_number:
      type: string
      label: ''
    user_id:
      type: string
      label: ''
    password:
      type: string
      label: ''
    connection_address:
      type: uri
      label: ''
    services:
      type: sequence
      label: ''
      sequence:
        type: string
        label: ''
    package_type:
      type: string
      label: ''
    pickup_type:
      type: string
      label: ''
    classification:
      type: string
      label: ''
    negotiated_rates:
      type: boolean
      label: ''
    residential_quotes:
      type: boolean
      label: ''
    all_in_one:
      type: integer
      label: ''
    unit_system:
      type: string
      label: ''
    insurance:
      type: boolean
      label: ''
    rate_markup_type:
      type: string
      label: ''
    rate_markup:
      type: integer
      label: ''
    weight_markup_type:
      type: string
      label: ''
    weight_markup:
      type: integer
      label: ''
    label_lifetime:
      type: integer
      label: ''
