# Schema for the configuration files of the Cart Links module.

uc_cart_links.settings:
  type: config_object
  mapping:
    add_show:
      type: boolean
      label: 'Display Cart Links product action when item is added to cart'
    track:
      type: boolean
      label: 'Track Cart Links clicks'
    empty:
      type: boolean
      label: 'Allow Cart Links to empty the cart'
    messages:
      type: string
      label: 'List of Cart Links messages and message ids'
    restrictions:
      type: string
      label: 'List of allowed Cart Links for this site'
    invalid_page:
      type: uri
      label: 'Redirect Uri for invalid Cart Links'
