uc_file.settings:
  type: config_object
  label: 'File download settings'
  mapping:
    base_dir:
      type: uri
      label: 'Base directory to store downloadable files'
    file_mask:
      type: string
      label: 'Regexp pattern to select file types'
    download_limit_number:
      type: integer
      label: 'Number of downloads allowed per user'
    download_limit_addresses:
      type: integer
      label: 'Number of IP addresses allowed per user'
    duration_qty:
      type: integer
      label: 'Download time limit'
    duration_granularity:
      type: string
      label: 'Unit value for download time limit'
    duplicate_warning:
      type: boolean
      label: 'Warning if already purchased'
