uc_product.settings:
  type: config_object
  label: 'Ubercart Product settings'
  mapping:
    add_to_cart_qty:
      type: boolean
      label: 'Default quantity to add to cart'
    update_node_view:
      type: boolean
      label: 'If Ajax is used to update product node view when add-to-cart fields change'

node.type.*.third_party.uc_product:
  type: mapping
  label: 'Product node type settings'
  mapping:
    product:
      type: boolean
      label: 'Is this a product type?'
    shippable:
      type: boolean
      label: 'Whether the product is shippable'
    image_field:
      type: string
      label: 'Name of product image field'
