# Schema for the views plugins of the uc_product module.

views.filter_value.uc_product_is_product:
  type: boolean
  label: 'Is a product'

views.field.uc_product_display_price:
  type: views.field.numeric
  label: 'Display price'
  mapping:
    format:
      type: string
      label: 'Number format to use'
