# Schema for the views plugins of the uc_order module.

views.field.uc_order_total:
  type: views.field.uc_price
  label: 'Order total'

views.field.uc_order_full_name:
  type: views_field
  label: 'Order full name'
  mapping:
    link_to_user:
      type: boolean
      label: 'Link this field to the customer'
    format:
      type: string
      label: 'Name format'

views.filter.uc_order_status:
  type: views.filter.in_operator
  label: 'Order status'

views.argument_validator.user_or_permission:
  type: views.argument_validator.none
  label: 'User or permission argument'
  mapping:
    perm:
      type: string
      label: 'Permission name'
