uc_order.status.*:
  type: config_entity
  label: 'Order status'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: 'Name'
    state:
      type: string
      label: 'Order state'
    weight:
      type: integer
      label: 'Weight'
    locked:
      type: boolean
      label: 'Locked'
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Default language'


uc_order.settings:
  type: config_object
  label: 'Order settings'
  mapping:
    default_state:
      type: mapping
      label: 'Default order state'
      mapping:
        canceled:
          type: string
          label: 'Order state label'

action.configuration.uc_order_delete_action:
  type: action_configuration_default
  label: 'Delete order configuration'

action.configuration.uc_order_print_action:
  type: action_configuration_default
  label: 'Print order configuration'

action.configuration.uc_order_set_order_status_action:
  type: action_configuration_default
  label: 'Set order status configuration'
  mapping:
    status:
      type: label
      label: 'Order status'
    notify:
      type: boolean
      label: 'Whether to send status change notification E-mail'
