uc_usps.settings:
  type: config_object
  label: 'Shipping quote method configuration settings'
  mapping:
    user_id:
      type: string
      label: ''
    online_rates:
      type: boolean
      label: ''
    all_in_one:
      type: integer
      label: ''
    insurance:
      type: boolean
      label: 'Add insurance'
    delivery_confirmation:
      type: boolean
      label: 'Use delivery confirmation'
    signature_confirmation:
      type: boolean
      label: 'Use signature confirmation'
    rate_markup_type:
      type: string
      label: ''
    rate_markup:
      type: float
      label: ''
    weight_markup_type:
      type: string
      label: ''
    weight_markup:
      type: float
      label: ''
    services:
      type: sequence
      label: 'USPS domestic service names'
      sequence:
        type: string
        label: 'Service name'
    env_services:
      type: sequence
      label: 'USPS domestic envelope service names'
      sequence:
        type: string
        label: 'Service name'
    intl_services:
      type: sequence
      label: 'USPS international service names'
      sequence:
        type: string
        label: 'Service name'
    intl_env_services:
      type: sequence
      label: 'USPS international envelope service names'
      sequence:
        type: string
        label: 'Service name'
