uc_catalog.settings:
  type: config_object
  label: 'Product catalog settings'
  mapping:
    breadcrumb:
      type: boolean
      label: ''
    display:
      type: string
      label: 'Path string'
    vocabulary:
      type: string
      label: 'Vocabulary name'
    expand_categories:
      type: boolean
      label: ''
    block_nodecount:
      type: boolean
      label: ''
