# Schema for the configuration files of the Cart Links module.

uc_stock.settings:
  type: config_object
  mapping:
    notify:
      type: boolean
      label: ''
    recipients:
      type: string
      label: ''

uc_stock.mail:
  type: config_object
  label: ''
  mapping:
    threshold_notification:
      type: mapping
      label: ''
      mapping:
        body:
          type: text
          label: ''
        subject:
          type: text
          label: ''
