<?php

/**
 * @file
 * Allow ubercart products to have stock levels associated with their SKU
 *
 * uc_stock enables ubercart to manage stock for products. Store admins can set
 * the stock levels on a product edit page and a threshold for each SKU value
 * When that threshold is reached admins can be optionally notified about the
 * current stock level. Store admins can view all stock levels in the reports
 * section of Ubercart.
 *
 * Development sponsored by the Ubercart project. http://www.ubercart.org
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uc_stock_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'uc_stock.edit':
      return '<p>' . t('To keep track of stock for a particular product SKU, make sure it is marked as active and enter a stock value. When the stock level drops below the threshold value, you can be notified based on your stock settings.') . '</p>';
    case 'admin/store/reports/stock':
    case 'admin/store/reports/stock/threshold':
      return '<p>' . t('This is the list of product SKUs that are currently active. Stock levels below their threshold have highlighted rows. Toggle the checkbox below to alter which stock levels are shown.') . '</p>';
  }
}

/**
 * Implements hook_mail().
 */
function uc_stock_mail($key, &$message, $params) {
  switch ($key) {
    case 'threshold':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Adjusts the product stock level by a set amount.
 *
 * @param $sku
 *   The product SKU of the stock level to adjust.
 * @param $qty
 *   The amount to add to or subtract from the stock level.
 * @param $check_active
 *   If FALSE, don't check if stock tracking is active for this SKU.
 */
function uc_stock_adjust($sku, $qty, $check_active = TRUE) {
  $stock = db_query("SELECT active, stock FROM {uc_product_stock} WHERE sku = :sku", [':sku' => $sku])->fetchObject();

  if ($check_active) {
    if (!$stock || !$stock->active) {
      return;
    }
  }

  db_update('uc_product_stock')
    ->expression('stock', 'stock + :qty', array(':qty' => $qty))
    ->condition('sku', $sku)
    ->execute();

  \Drupal::moduleHandler()->invokeAll('uc_stock_adjusted', array($sku, $stock->stock, $qty));
}

/**
 * Sets the product stock level.
 *
 * @param $sku
 *   The product SKU of the stock level to set.
 * @param $qty
 *   The number of items in stock.
 */
function uc_stock_set($sku, $qty) {
  db_update('uc_product_stock')
    ->fields(array('stock' => $qty))
    ->condition('sku', $sku)
    ->execute();
}

/**
 * Gets the stock level of a particular product SKU.
 *
 * @param $sku
 *   The Ubercart product SKU of the stock level to return.
 *
 * @return
 *   The SKU's stock level, or FALSE if not active.
 */
function uc_stock_level($sku) {
  $stock = db_query("SELECT active, stock FROM {uc_product_stock} WHERE sku = :sku", [':sku' => $sku])->fetchObject();

  if ($stock && $stock->active) {
    return $stock->stock;
  }

  return FALSE;
}

/**
 * Checks if a SKU has an active stock record.
 *
 * @param $sku
 *   The Ubercart product SKU to check
 *
 * @return
 *   Boolean indicating whether or not the sku has an active stock record.
 */
function uc_stock_is_active($sku) {
  return (bool) db_query("SELECT active FROM {uc_product_stock} WHERE sku = :sku", [':sku' => $sku])->fetchField();
}

/**
 * Emails administrator regarding any stock level thresholds hit.
 *
 * @param $order
 *   The order object that tripped the threshold limit.
 * @param $node
 *   The node object that is associated with the SKU/model.
 * @param $stock
 *   The stock level object that contains the stock level and SKU.
 *
 * @return
 *   The result of \Drupal::service('plugin.manager.mail')->mail().
 */
function _uc_stock_send_mail($order, $node, $stock) {
  $token_service = \Drupal::token();

  $account = $order->getOwner();
  $token_filters = array('uc_order' => $order, 'user' => $account, 'uc_stock' => $stock, 'node' => $node);

  $to = \Drupal::config('uc_stock.settings')->get('recipients');
  $to = $token_service->replace($to, $token_filters);
  $to = explode(',', $to);

  $from = uc_store_email_from();

  $mail_config = \Drupal::config('uc_stock.mail');
  $subject = $mail_config->get('threshold_notification.subject');
  $subject = $token_service->replace($subject, $token_filters);
  $body = $mail_config->get('threshold_notification.body');
  $body = $token_service->replace($body, $token_filters);

  // Send to each recipient.
  foreach ($to as $email) {
    $sent = \Drupal::service('plugin.manager.mail')->mail('uc_stock', 'threshold', $email, uc_store_mail_recipient_langcode($email), array('body' => $body, 'subject' => $subject, 'order' => $order, 'stock' => $stock), $from);

    if (!$sent['result']) {
      \Drupal::logger('uc_stock')->error('Attempt to e-mail @email concerning stock level on sku @sku failed.', ['@email' => $email, '@sku' => $stock->sku]);
    }
  }
}

/**
 * Implements hook_uc_checkout_complete().
 *
 * Decrements stock if Rules is not installed.
 */
function uc_stock_uc_checkout_complete($order) {
  // @todo: When Rules actually works, we can uncomment this conditional.
  //if (!\Drupal::moduleHandler()->moduleExists('rules')) {
    array_walk($order->products, 'uc_stock_adjust_product_stock', $order);
  //}
}

/**
 * Decrement a product's stock.
 *
 * @param $product
 *   The product whose stock is being adjusted.
 * @param $key
 *   Internal, so this function can be used as a callback of array_walk().
 * @param $order
 *   Order object.
 */
function uc_stock_adjust_product_stock($product, $key, $order) {
  // Product has an active stock?
  if (!uc_stock_is_active($product->model->value)) {
    return;
  }

  // Do nothing if decrement quantity is 0.
  if ($product->qty->value == 0) {
    return;
  }

  // Adjust the product's stock.
  uc_stock_adjust($product->model->value, -$product->qty->value);

  // Load the new stock record.
  $stock = db_query("SELECT * FROM {uc_product_stock} WHERE sku = :sku", [':sku' => $product->model->value])->fetchObject();

  // Should we notify?
  if (\Drupal::config('uc_stock.settings')->get('notify') && $stock->stock <= $stock->threshold) {
    $node = node_load($product->nid->target_id);
    _uc_stock_send_mail($order, $node, $stock);
  }

  // Save a comment about the stock level.
  uc_order_comment_save($order->id(), 0, t('The stock level for %model_name has been @action to @qty.', ['%model_name' => $product->model->value, '@qty' => $stock->stock, '@action' => (-$product->qty->value <= 0) ? t('decreased') : t('increased')]));
}

/**
 * Increment a product's stock.
 */
function uc_stock_increment_product_stock($product, $key, $order) {
  $product->qty = -$product->qty;
  return uc_stock_adjust_product_stock($product, $key, $order);
}
