# Schema for the configuration files of the Store module.

uc_store.settings:
  type: config_object
  label: 'Store settings'
  mapping:
    name:
      type: string
      label: ''
    mail:
      type: string
      label: ''
    mail_include_name:
      type: boolean
      label: ''
    phone:
      type: string
      label: ''
    fax:
      type: string
      label: ''
    help_page:
      type: uri
      label: ''
    address:
      type: mapping
      label: ''
      mapping:
        street1:
          type: string
          label: ''
        street2:
          type: string
          label: ''
        city:
          type: string
          label: ''
        zone:
          type: string
          label: ''
        country:
          type: string
          label: ''
        postal_code:
          type: string
          label: ''
    address_fields:
      type: mapping
      label: ''
      mapping:
        first_name:
          type: mapping
          label: ''
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        last_name:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        company:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        street1:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        street2:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        city:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        zone:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        country:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        postal_code:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
        phone:
          type: mapping
          label:
          mapping:
            required:
              type: boolean
              label: 'Required'
            status:
              type: boolean
              label: 'Enabled'
            weight:
              type: integer
              label: 'Listing weight'
    currency:
      type: mapping
      label:
      mapping:
        code:
          type: string
          label: '3-character currency code'
        symbol:
          type: string
          label: 'Currency symbol'
        symbol_after:
          type: boolean
          label: 'Currency symbol position'
        thousands_marker:
          type: string
          label: 'Currency thousands marker'
        decimal_marker:
          type: string
          label: 'Currency decimal marker'
        precision:
          type: integer
          label: 'Currency decimal places'
    weight:
      type: mapping
      label:
      mapping:
        units:
          type: string
          label: 'Default weight units'
        thousands_marker:
          type: string
          label: 'Weight thousands marker'
        decimal_marker:
          type: string
          label: 'Weight decimal marker'
        precision:
          type: integer
          label: 'Weight decimal places'
    length:
      type: mapping
      label:
      mapping:
        units:
          type: string
          label: 'Default length units'
        thousands_marker:
          type: string
          label: 'Length thousands marker'
        decimal_marker:
          type: string
          label: 'Length decimal marker'
        precision:
          type: integer
          label: 'Length decimal places'
    customer_address:
      type: string
      label: 'Address type to use'
    capitalize_address:
      type: boolean
      label: 'Display address in all capital letters'
    footer_message:
      type: boolean
      label: 'Display footer message'
