# Schema for the views plugins of the uc_store module.

views.field.uc_price:
  type: views.field.numeric
  label: 'Price'
  mapping:
    format:
      type: string
      label: 'Number format to use'
