# Schema for the views plugins of the uc_report module.

uc_report.settings:
  type: config_object
  label: 'Report settings'
  mapping:
    table_size:
      type: integer
      label: 'Number of records shown per page'
    reported_statuses:
      type: sequence
      label: 'Orders statuses to include in reports'
      sequence:
        type: label
        label: 'Orders status name'
