# Schema for the configuration files of the uc_payment_pack module.

payment_method.settings.cod:
  type: mapping
  label: 'COD payment method configuration settings'
  mapping:
    policy:
      type: text
      label: 'COD payment policy message'
    max_order:
      type: float
      label: 'Maximum currency amount for COD'
    delivery_date:
      type: boolean
      label: 'Whether to ask customer for desired delivery date'

payment_method.settings.check:
  type: mapping
  label: 'Check payment method configuration settings'
  mapping:
    policy:
      type: text
      label: 'Payment policy message'
    name:
      type: string
      label: 'Payee name'
    address:
      type: mapping
      label: 'Accounts receivable address'
      mapping:
        name:
          type: string
          label: 'Contact name'
        company:
          type: string
          label: 'Company name'
        street1:
          type: string
          label: 'First street line'
        street2:
          type: string
          label: 'Second street line'
        city:
          type: string
          label: 'City'
        zone:
          type: string
          label: 'State/Provence'
        postal_code:
          type: string
          label: 'Postal code'
        country:
          type: string
          label: 'Country ID'

payment_method.settings.other:
  type: mapping
  label: 'Other method configuration settings'
  mapping:
